### PR TITLE
fixed duplicate websockets on page navigation

### LINKED ISSUE #99: Duplicate web sockets are opened when navigating to user preferences

### PR DESCRIPTION
**Pull request by paynejacob**
closes #99

### CODE REVIEW

File: web/speakerbob/src/App.vue [hunk 1]
```diff
@@ -2,7 +2,7 @@
   <v-app>
     <v-app-bar app dark color="primary">
       <div class="d-flex align-center">
-          <v-toolbar-title @click="$router.push('/')">
```
Comment (paynejacob) [inline web/speakerbob/src/App.vue:5]: add back

File: web/speakerbob/src/plugins/player.ts [hunk 2]
```diff
@@ -1,35 +1,53 @@
...
     this.audio.src = ''
-    this.audio.play()
-  }
 
-  public static install (Vue: typeof _Vue, _options?: PlayerOptions) {
-    Vue.prototype.$audioPlayer = new Player()
+    try {
+      await this.audio.play()
+    } catch (e) {
+      console.log(typeof e)
```
Comment (paynejacob) [inline web/speakerbob/src/plugins/player.ts:40]: no log
